PR-template-added
dokc/dokc.github.io pull request #55
Opened 2022-03-21 16:11 UTC by vish-han

I have added the PR template which was not there previously , Please review the code and let me know if u want some changes✌️😊.

2022-03-21 18:31 UTC, cnu1812 commented
You worked under wrong directory. Change the directory else template won't work.

2022-03-22 03:35 UTC, vish-han commented
Oh sorry my bad , can u please let me know in which directory I should add this file😃

2022-03-22 03:49 UTC, subhamgcon requested changes
Take the code out of the workflow folder and make another folder as PULL_RUQUEST_TEMPLATE and then push the md file in that folder to make it work

2022-03-23 05:15 UTC, AbhijithGanesh requested changes

2022-03-23 05:15 UTC, AbhijithGanesh commented on .github/workflows/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] My changes generate no new warnings
This is in the wrong directory, `PULL_REQUEST_TEMPLATE/` is the correct directory to have the template. Please make the changes :)

2022-03-26 07:34 UTC, gullapalli9482 commented
Is there any pending work to be done?

2022-03-26 07:38 UTC, cnu1812 commented
> Is there any pending work to be done?

Has to change the working directory

2022-03-26 07:38 UTC, vish-han commented
@cnu1812  im making changes rn

2022-03-26 07:42 UTC, vish-han commented
@AbhijithGanesh Can u please review it  now. please.?

2022-03-26 08:05 UTC, AbhijithGanesh approved these changes
LGTM

2022-03-27 07:15 UTC, cnu1812 approved these changes

2022-03-27 07:16 UTC, merged